### PR TITLE
Added search template controller with basic functions

### PR DESCRIPTION
**Pull request by chriskwong91**
Includes the text field, add button, and the layout of rendering the added ingredients.

### CODE REVIEW

**Comment by chriskwong91** [comment]
resolves#17

**Comment by chriskwong91** [comment]
Don't think that worked

**Comment by chriskwong91** [comment]
Don't merge this yet, need to correct names with the services

**Comment by chriskwong91** [comment]
ready to be reviewed

**Comment by brianzhou13** [comment]
There seems to be some small bugs with this page. I'm going to try and add some fixes to this page to try and get the UI flowing. :)

**Comment by brianzhou13** [comment]
There seems to be some small bugs with this page. I'm going to try and add some fixes to this page to try and get the UI flowing. :) @chriskwong91

**Pull request merged**
